import { Metadata } from "next";
import { ReactChildren } from "@open-press/interfaces";

import "./globals.css";
import { nunito } from "@open-press/components/server";
import "@tabler/icons-webfont/tabler-icons.min.css";

export const metadata: Metadata = {
	title:       "Welcome to front-end",
	description: "Generated by create-nx-workspace",
};

export default function RootLayout(
	{ children }: ReactChildren,
): JSX.Element {
	return (
		<html
			lang="en"
			className={"scroll-smooth"}
		>
			<body className={`text-primary-800 ${nunito.className}`}>
				{children}
			</body>
		</html>
	);
}
