import { Metadata } from "next";
import { ReactChildren } from "@override/open-press-interfaces";
import { Providers } from "./providers";

export const metadata: Metadata = {
	title:       "Welcome to front-end",
	description: "Generated by create-nx-workspace",
};

export default function RootLayout(
	{ children }: ReactChildren,
): JSX.Element {
	return (
		<html lang="en">
			<body>
				<Providers>
					{children}
				</Providers>
			</body>
		</html>
	);
}
